name: Build and Deploy to AWS

env:
  NODE_VERSION: '16.0'               # set this to the node version to use

run-name: Building and deploying to AWS S3

on:
  push:
    branches: ['main']
  workflow_dispatch:
  
permissions: 
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./build
    
  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
      
    runs-on: ubuntu-latest
    needs: [Build]
    environment: Production
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./build
          
      - name: action-upload-to-s3
        uses: wixplosives/action-upload-to-s3@v10
        with:
          # AWS Access key id (short one)
          accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID}}
          
          # AWS Secret access key  (long one)
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          
          # bucket name
          awsBucket: ciwgo.frontend

          # sourcefolder to upload
          sourceFolder: build

          
